channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - bcftools=1.19
  - samtools=1.19.2
  - bwa=0.7.18
  - pip:
    - pysam==0.22
    - Click==8.1.8
    - biopython==1.85
    - pandas==2.2.3
