Bins:
  015_E1.bin.1:  ../allbins.metaWRAP/015_E1.bin.1.fa
  015_E1.bin.2:  ../allbins.metaWRAP/015_E1.bin.2.fa
  015_E1.bin.3:  ../allbins.metaWRAP/015_E1.bin.3.fa
  015_E1.bin.4:  ../allbins.metaWRAP/015_E1.bin.4.fa
  015_E1.bin.5:  ../allbins.metaWRAP/015_E1.bin.5.fa
  015_E1.bin.6:  ../allbins.metaWRAP/015_E1.bin.6.fa
  015_E1.bin.7:  ../allbins.metaWRAP/015_E1.bin.7.fa
  015_E1.bin.8:  ../allbins.metaWRAP/015_E1.bin.8.fa
  015_E1.bin.9:  ../allbins.metaWRAP/015_E1.bin.9.fa
  015_E2.bin.1:  ../allbins.metaWRAP/015_E2.bin.1.fa
  015_E2.bin.2:  ../allbins.metaWRAP/015_E2.bin.2.fa
  015_E2.bin.3:  ../allbins.metaWRAP/015_E2.bin.3.fa
  015_E2.bin.4:  ../allbins.metaWRAP/015_E2.bin.4.fa
  015_E2.bin.5:  ../allbins.metaWRAP/015_E2.bin.5.fa
  016_E1.bin.1:  ../allbins.metaWRAP/016_E1.bin.1.fa
  016_E1.bin.2:  ../allbins.metaWRAP/016_E1.bin.2.fa
  016_E1.bin.3:  ../allbins.metaWRAP/016_E1.bin.3.fa
  016_E1.bin.4:  ../allbins.metaWRAP/016_E1.bin.4.fa
  016_E2.bin.1:  ../allbins.metaWRAP/016_E2.bin.1.fa
  016_E2.bin.2:  ../allbins.metaWRAP/016_E2.bin.2.fa
  016_E2.bin.3:  ../allbins.metaWRAP/016_E2.bin.3.fa
  016_E2.bin.4:  ../allbins.metaWRAP/016_E2.bin.4.fa
  016_E2.bin.5:  ../allbins.metaWRAP/016_E2.bin.5.fa
  016_E2.bin.6:  ../allbins.metaWRAP/016_E2.bin.6.fa
  018_E1.bin.1:  ../allbins.metaWRAP/018_E1.bin.1.fa
  018_E1.bin.2:  ../allbins.metaWRAP/018_E1.bin.2.fa
  018_E1.bin.3:  ../allbins.metaWRAP/018_E1.bin.3.fa
  018_E2.bin.1:  ../allbins.metaWRAP/018_E2.bin.1.fa
  018_E2.bin.2:  ../allbins.metaWRAP/018_E2.bin.2.fa
  018_E2.bin.3:  ../allbins.metaWRAP/018_E2.bin.3.fa
  018_E2.bin.4:  ../allbins.metaWRAP/018_E2.bin.4.fa
  018_E2.bin.5:  ../allbins.metaWRAP/018_E2.bin.5.fa
  018_E2.bin.6:  ../allbins.metaWRAP/018_E2.bin.6.fa
  018_E2.bin.7:  ../allbins.metaWRAP/018_E2.bin.7.fa
  018_E2.bin.8:  ../allbins.metaWRAP/018_E2.bin.8.fa
  018_E2.bin.9:  ../allbins.metaWRAP/018_E2.bin.9.fa
  021_E1.bin.1:  ../allbins.metaWRAP/021_E1.bin.1.fa
  021_E1.bin.2:  ../allbins.metaWRAP/021_E1.bin.2.fa
  021_E1.bin.3:  ../allbins.metaWRAP/021_E1.bin.3.fa
  021_E1.bin.4:  ../allbins.metaWRAP/021_E1.bin.4.fa
  021_E1.bin.5:  ../allbins.metaWRAP/021_E1.bin.5.fa
  021_E1.bin.6:  ../allbins.metaWRAP/021_E1.bin.6.fa
  021_E1.bin.7:  ../allbins.metaWRAP/021_E1.bin.7.fa
  021_E1.bin.8:  ../allbins.metaWRAP/021_E1.bin.8.fa
  021_E1.bin.9:  ../allbins.metaWRAP/021_E1.bin.9.fa
  021_E2.bin.1:  ../allbins.metaWRAP/021_E2.bin.1.fa
  021_E2.bin.2:  ../allbins.metaWRAP/021_E2.bin.2.fa
  021_E2.bin.3:  ../allbins.metaWRAP/021_E2.bin.3.fa
  021_E2.bin.5:  ../allbins.metaWRAP/021_E2.bin.5.fa
  021_E2.bin.6:  ../allbins.metaWRAP/021_E2.bin.6.fa
  021_E2.bin.7:  ../allbins.metaWRAP/021_E2.bin.7.fa
  021_E2.bin.8:  ../allbins.metaWRAP/021_E2.bin.8.fa
  021_E2.bin.9:  ../allbins.metaWRAP/021_E2.bin.9.fa
  021_E2.bin.10:  ../allbins.metaWRAP/021_E2.bin.10.fa
  021_E2.bin.11:  ../allbins.metaWRAP/021_E2.bin.11.fa
  021_E2.bin.12:  ../allbins.metaWRAP/021_E2.bin.12.fa
  034_E1.bin.1:  ../allbins.metaWRAP/034_E1.bin.1.fa
  034_E1.bin.2:  ../allbins.metaWRAP/034_E1.bin.2.fa
  034_E1.bin.3:  ../allbins.metaWRAP/034_E1.bin.3.fa
  034_E1.bin.4:  ../allbins.metaWRAP/034_E1.bin.4.fa
  034_E1.bin.5:  ../allbins.metaWRAP/034_E1.bin.5.fa
  034_E1.bin.6:  ../allbins.metaWRAP/034_E1.bin.6.fa
  034_E1.bin.7:  ../allbins.metaWRAP/034_E1.bin.7.fa
  034_E1.bin.8:  ../allbins.metaWRAP/034_E1.bin.8.fa
  034_E1.bin.9:  ../allbins.metaWRAP/034_E1.bin.9.fa
  034_E1.bin.10:  ../allbins.metaWRAP/034_E1.bin.10.fa
  034_E1.bin.11:  ../allbins.metaWRAP/034_E1.bin.11.fa
  034_E2.bin.1:  ../allbins.metaWRAP/034_E2.bin.1.fa
  034_E2.bin.2:  ../allbins.metaWRAP/034_E2.bin.2.fa
  034_E2.bin.3:  ../allbins.metaWRAP/034_E2.bin.3.fa
  034_E2.bin.4:  ../allbins.metaWRAP/034_E2.bin.4.fa
  034_E2.bin.5:  ../allbins.metaWRAP/034_E2.bin.5.fa
  034_E2.bin.6:  ../allbins.metaWRAP/034_E2.bin.6.fa
  034_E2.bin.7:  ../allbins.metaWRAP/034_E2.bin.7.fa
  034_E2.bin.8:  ../allbins.metaWRAP/034_E2.bin.8.fa
  034_E2.bin.9:  ../allbins.metaWRAP/034_E2.bin.9.fa
  034_E2.bin.10:  ../allbins.metaWRAP/034_E2.bin.10.fa
  034_E2.bin.11:  ../allbins.metaWRAP/034_E2.bin.11.fa
  044_E1.bin.1:  ../allbins.metaWRAP/044_E1.bin.1.fa
  044_E1.bin.2:  ../allbins.metaWRAP/044_E1.bin.2.fa
  044_E1.bin.3:  ../allbins.metaWRAP/044_E1.bin.3.fa
  044_E1.bin.4:  ../allbins.metaWRAP/044_E1.bin.4.fa
  044_E1.bin.5:  ../allbins.metaWRAP/044_E1.bin.5.fa
  044_E1.bin.6:  ../allbins.metaWRAP/044_E1.bin.6.fa
  044_E1.bin.7:  ../allbins.metaWRAP/044_E1.bin.7.fa
  044_E1.bin.8:  ../allbins.metaWRAP/044_E1.bin.8.fa
  044_E2.bin.1:  ../allbins.metaWRAP/044_E2.bin.1.fa
  044_E2.bin.2:  ../allbins.metaWRAP/044_E2.bin.2.fa
  044_E2.bin.3:  ../allbins.metaWRAP/044_E2.bin.3.fa
  044_E2.bin.4:  ../allbins.metaWRAP/044_E2.bin.4.fa
  044_E2.bin.5:  ../allbins.metaWRAP/044_E2.bin.5.fa
  044_E2.bin.6:  ../allbins.metaWRAP/044_E2.bin.6.fa
  044_E2.bin.7:  ../allbins.metaWRAP/044_E2.bin.7.fa
  044_E2.bin.9:  ../allbins.metaWRAP/044_E2.bin.9.fa
  044_E2.bin.10:  ../allbins.metaWRAP/044_E2.bin.10.fa
  044_E2.bin.11:  ../allbins.metaWRAP/044_E2.bin.11.fa
  044_E2.bin.12:  ../allbins.metaWRAP/044_E2.bin.12.fa
  046_E1.bin.1:  ../allbins.metaWRAP/046_E1.bin.1.fa
  046_E1.bin.2:  ../allbins.metaWRAP/046_E1.bin.2.fa
  046_E1.bin.3:  ../allbins.metaWRAP/046_E1.bin.3.fa
  046_E1.bin.4:  ../allbins.metaWRAP/046_E1.bin.4.fa
  046_E2.bin.1:  ../allbins.metaWRAP/046_E2.bin.1.fa
  046_E2.bin.2:  ../allbins.metaWRAP/046_E2.bin.2.fa
  046_E2.bin.3:  ../allbins.metaWRAP/046_E2.bin.3.fa
  046_E2.bin.4:  ../allbins.metaWRAP/046_E2.bin.4.fa
  046_E2.bin.5:  ../allbins.metaWRAP/046_E2.bin.5.fa
  B1_E1.bin.1:  ../allbins.metaWRAP/B1_E1.bin.1.fa
  B1_E1.bin.2:  ../allbins.metaWRAP/B1_E1.bin.2.fa
  B1_E1.bin.3:  ../allbins.metaWRAP/B1_E1.bin.3.fa
  B1_E1.bin.4:  ../allbins.metaWRAP/B1_E1.bin.4.fa
  B1_E1.bin.5:  ../allbins.metaWRAP/B1_E1.bin.5.fa
  B1_E1.bin.6:  ../allbins.metaWRAP/B1_E1.bin.6.fa
  B1_E2.bin.1:  ../allbins.metaWRAP/B1_E2.bin.1.fa
  B1_E2.bin.2:  ../allbins.metaWRAP/B1_E2.bin.2.fa
  B1_E2.bin.3:  ../allbins.metaWRAP/B1_E2.bin.3.fa
  B1_E2.bin.4:  ../allbins.metaWRAP/B1_E2.bin.4.fa
  B1_E2.bin.5:  ../allbins.metaWRAP/B1_E2.bin.5.fa
  B1_E2.bin.6:  ../allbins.metaWRAP/B1_E2.bin.6.fa
  B1_E2.bin.7:  ../allbins.metaWRAP/B1_E2.bin.7.fa
  B1_E2.bin.8:  ../allbins.metaWRAP/B1_E2.bin.8.fa
  B1_E2.bin.9:  ../allbins.metaWRAP/B1_E2.bin.9.fa
  B1_E2.bin.10:  ../allbins.metaWRAP/B1_E2.bin.10.fa
  B1_E2.bin.11:  ../allbins.metaWRAP/B1_E2.bin.11.fa
  Co-assembly.bin.1:  ../allbins.metaWRAP/Co-assembly.bin.1.fa
  Co-assembly.bin.2:  ../allbins.metaWRAP/Co-assembly.bin.2.fa
  Co-assembly.bin.3:  ../allbins.metaWRAP/Co-assembly.bin.3.fa
  Co-assembly.bin.4:  ../allbins.metaWRAP/Co-assembly.bin.4.fa
  Co-assembly.bin.5:  ../allbins.metaWRAP/Co-assembly.bin.5.fa
  Co-assembly.bin.6:  ../allbins.metaWRAP/Co-assembly.bin.6.fa
  Co-assembly.bin.7:  ../allbins.metaWRAP/Co-assembly.bin.7.fa
  Co-assembly.bin.8:  ../allbins.metaWRAP/Co-assembly.bin.8.fa
  Co-assembly.bin.9:  ../allbins.metaWRAP/Co-assembly.bin.9.fa
  Co-assembly.bin.10:  ../allbins.metaWRAP/Co-assembly.bin.10.fa
  Co-assembly.bin.11:  ../allbins.metaWRAP/Co-assembly.bin.11.fa
  Co-assembly.bin.12:  ../allbins.metaWRAP/Co-assembly.bin.12.fa
  Co-assembly.bin.13:  ../allbins.metaWRAP/Co-assembly.bin.13.fa
  Co-assembly.bin.14:  ../allbins.metaWRAP/Co-assembly.bin.14.fa
  Co-assembly.bin.15:  ../allbins.metaWRAP/Co-assembly.bin.15.fa
  Co-assembly.bin.17:  ../allbins.metaWRAP/Co-assembly.bin.17.fa
  Co-assembly.bin.18:  ../allbins.metaWRAP/Co-assembly.bin.18.fa
  Co-assembly.bin.19:  ../allbins.metaWRAP/Co-assembly.bin.19.fa
  Co-assembly.bin.20:  ../allbins.metaWRAP/Co-assembly.bin.20.fa
  Co-assembly.bin.21:  ../allbins.metaWRAP/Co-assembly.bin.21.fa
  Co-assembly.bin.22:  ../allbins.metaWRAP/Co-assembly.bin.22.fa
  Co-assembly.bin.23:  ../allbins.metaWRAP/Co-assembly.bin.23.fa
  Co-assembly.bin.24:  ../allbins.metaWRAP/Co-assembly.bin.24.fa
  Co-assembly.bin.25:  ../allbins.metaWRAP/Co-assembly.bin.25.fa
  Co-assembly.bin.26:  ../allbins.metaWRAP/Co-assembly.bin.26.fa
  Co-assembly.bin.27:  ../allbins.metaWRAP/Co-assembly.bin.27.fa
  Co-assembly.bin.28:  ../allbins.metaWRAP/Co-assembly.bin.28.fa
  Co-assembly.bin.29:  ../allbins.metaWRAP/Co-assembly.bin.29.fa
  Co-assembly.bin.30:  ../allbins.metaWRAP/Co-assembly.bin.30.fa
  Co-assembly.bin.31:  ../allbins.metaWRAP/Co-assembly.bin.31.fa
  Co-assembly.bin.32:  ../allbins.metaWRAP/Co-assembly.bin.32.fa
  Co-assembly.bin.33:  ../allbins.metaWRAP/Co-assembly.bin.33.fa
  Co-assembly.bin.34:  ../allbins.metaWRAP/Co-assembly.bin.34.fa
  Co-assembly.bin.35:  ../allbins.metaWRAP/Co-assembly.bin.35.fa
  Co-assembly.bin.36:  ../allbins.metaWRAP/Co-assembly.bin.36.fa
  Co-assembly.bin.37:  ../allbins.metaWRAP/Co-assembly.bin.37.fa
  Co-assembly.bin.38:  ../allbins.metaWRAP/Co-assembly.bin.38.fa
  Co-assembly.bin.39:  ../allbins.metaWRAP/Co-assembly.bin.39.fa
  Co-assembly.bin.40:  ../allbins.metaWRAP/Co-assembly.bin.40.fa
  Co-assembly.bin.41:  ../allbins.metaWRAP/Co-assembly.bin.41.fa
  Co-assembly.bin.42:  ../allbins.metaWRAP/Co-assembly.bin.42.fa
  Co-assembly.bin.43:  ../allbins.metaWRAP/Co-assembly.bin.43.fa
  Co-assembly.bin.44:  ../allbins.metaWRAP/Co-assembly.bin.44.fa
  Co-assembly.bin.45:  ../allbins.metaWRAP/Co-assembly.bin.45.fa
  Co-assembly.bin.46:  ../allbins.metaWRAP/Co-assembly.bin.46.fa
  Co-assembly.bin.47:  ../allbins.metaWRAP/Co-assembly.bin.47.fa
  Co-assembly.bin.48:  ../allbins.metaWRAP/Co-assembly.bin.48.fa
  Co-assembly.bin.49:  ../allbins.metaWRAP/Co-assembly.bin.49.fa
  Co-assembly.bin.50:  ../allbins.metaWRAP/Co-assembly.bin.50.fa
  Co-assembly.bin.52:  ../allbins.metaWRAP/Co-assembly.bin.52.fa
  Co-assembly.bin.53:  ../allbins.metaWRAP/Co-assembly.bin.53.fa
  Co-assembly.bin.54:  ../allbins.metaWRAP/Co-assembly.bin.54.fa
  Co-assembly.bin.55:  ../allbins.metaWRAP/Co-assembly.bin.55.fa
  Co-assembly.bin.56:  ../allbins.metaWRAP/Co-assembly.bin.56.fa
  Co-assembly.bin.58:  ../allbins.metaWRAP/Co-assembly.bin.58.fa
  Co-assembly.bin.59:  ../allbins.metaWRAP/Co-assembly.bin.59.fa
  Co-assembly.bin.60:  ../allbins.metaWRAP/Co-assembly.bin.60.fa
  Co-assembly.bin.61:  ../allbins.metaWRAP/Co-assembly.bin.61.fa
  Co-assembly.bin.62:  ../allbins.metaWRAP/Co-assembly.bin.62.fa
  Co-assembly.bin.63:  ../allbins.metaWRAP/Co-assembly.bin.63.fa
  Co-assembly.bin.64:  ../allbins.metaWRAP/Co-assembly.bin.64.fa
  Co-assembly.bin.65:  ../allbins.metaWRAP/Co-assembly.bin.65.fa
  Co-assembly.bin.66:  ../allbins.metaWRAP/Co-assembly.bin.66.fa
  Co-assembly.bin.67:  ../allbins.metaWRAP/Co-assembly.bin.67.fa
  Co-assembly.bin.68:  ../allbins.metaWRAP/Co-assembly.bin.68.fa
  Co-assembly.bin.69:  ../allbins.metaWRAP/Co-assembly.bin.69.fa
  Co-assembly.bin.70:  ../allbins.metaWRAP/Co-assembly.bin.70.fa
  Co-assembly.bin.71:  ../allbins.metaWRAP/Co-assembly.bin.71.fa
  Co-assembly.bin.72:  ../allbins.metaWRAP/Co-assembly.bin.72.fa
  Co-assembly.bin.73:  ../allbins.metaWRAP/Co-assembly.bin.73.fa
  Co-assembly.bin.74:  ../allbins.metaWRAP/Co-assembly.bin.74.fa
  Co-assembly.bin.75:  ../allbins.metaWRAP/Co-assembly.bin.75.fa
  Co-assembly.bin.76:  ../allbins.metaWRAP/Co-assembly.bin.76.fa
  Co-assembly.bin.78:  ../allbins.metaWRAP/Co-assembly.bin.78.fa
  Co-assembly.bin.79:  ../allbins.metaWRAP/Co-assembly.bin.79.fa
  Co-assembly.bin.80:  ../allbins.metaWRAP/Co-assembly.bin.80.fa
  Co-assembly.bin.81:  ../allbins.metaWRAP/Co-assembly.bin.81.fa
  Co-assembly.bin.82:  ../allbins.metaWRAP/Co-assembly.bin.82.fa
  Co-assembly.bin.83:  ../allbins.metaWRAP/Co-assembly.bin.83.fa
  Co-assembly.bin.84:  ../allbins.metaWRAP/Co-assembly.bin.84.fa
  Co-assembly.bin.85:  ../allbins.metaWRAP/Co-assembly.bin.85.fa
  Co-assembly.bin.86:  ../allbins.metaWRAP/Co-assembly.bin.86.fa
  Co-assembly.bin.87:  ../allbins.metaWRAP/Co-assembly.bin.87.fa
  Co-assembly.bin.88:  ../allbins.metaWRAP/Co-assembly.bin.88.fa
  Co-assembly.bin.89:  ../allbins.metaWRAP/Co-assembly.bin.89.fa
  R3_E1.bin.1:  ../allbins.metaWRAP/R3_E1.bin.1.fa
  R3_E1.bin.2:  ../allbins.metaWRAP/R3_E1.bin.2.fa
  R3_E1.bin.3:  ../allbins.metaWRAP/R3_E1.bin.3.fa
  R3_E1.bin.4:  ../allbins.metaWRAP/R3_E1.bin.4.fa
  R3_E1.bin.5:  ../allbins.metaWRAP/R3_E1.bin.5.fa
  R3_E1.bin.6:  ../allbins.metaWRAP/R3_E1.bin.6.fa
  R3_E1.bin.7:  ../allbins.metaWRAP/R3_E1.bin.7.fa
  R3_E1.bin.8:  ../allbins.metaWRAP/R3_E1.bin.8.fa
  R3_E1.bin.9:  ../allbins.metaWRAP/R3_E1.bin.9.fa
  R3_E1.bin.10:  ../allbins.metaWRAP/R3_E1.bin.10.fa
  R3_E1.bin.11:  ../allbins.metaWRAP/R3_E1.bin.11.fa
  R3_E2.bin.2:  ../allbins.metaWRAP/R3_E2.bin.2.fa
  R3_E2.bin.3:  ../allbins.metaWRAP/R3_E2.bin.3.fa
  R3_E2.bin.4:  ../allbins.metaWRAP/R3_E2.bin.4.fa
  R3_E2.bin.5:  ../allbins.metaWRAP/R3_E2.bin.5.fa
  R3_E2.bin.6:  ../allbins.metaWRAP/R3_E2.bin.6.fa
  R3_E2.bin.7:  ../allbins.metaWRAP/R3_E2.bin.7.fa
  R3_E2.bin.8:  ../allbins.metaWRAP/R3_E2.bin.8.fa
  R3_E2.bin.9:  ../allbins.metaWRAP/R3_E2.bin.9.fa
  R3_E2.bin.10:  ../allbins.metaWRAP/R3_E2.bin.10.fa
